[General]
name = "Wiseby Design"

[Footer]
copy-text = "Copyright 2024 © WisebyDesign Sweden"

[CompanyDetails]
address = "Flårekulla 104 52375 Dalum"
email = "lucas.wiseby@wisebydesign.se"
order-email = "order@wisebydesign.se"
org-number = "900618-5335"
vat-number = "SE900618533501"
bank-transfer-number = "520-9473"
